name: CraftClean
version: 1.0.1
author: BaneOfSmite
main: me.baneofsmite.craftclean.Main
description: Bane's CraftClean Plugin

commands:
  craftclean:
    description: Toggles CraftClean
    usage: /<command>
    permission: Bane.Op

permissions:
  Bane.Op:
    description: Gives access to Bane Plugins Commands
